---
- hosts: kafka
  become: yes
  pre_tasks:
    - name: Uncompressing and copying to system path
      unarchive:
        src: https://sunbirdpublic.blob.core.windows.net/installation/jre-8u144-linux-x64.tar.gz
        dest: /opt/
        remote_src: yes
        keep_newer: yes
      become: yes
      register: tar
    - name: Updating java jre to system path
      become: yes
      shell: update-alternatives --install /usr/bin/java java /opt/jre1.8.0_144/bin/java 9999
  roles:
    - zookeeper
    - ansible-kafka-upgrade
